# Generated by Django 5.0.3 on 2026-08-12 17:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_outletsettings_landing_cost_include_freight_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SandboxConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('_api_key_encrypted', models.CharField(blank=True, default='', max_length=255)),
                ('_api_secret_encrypted', models.CharField(blank=True, default='', max_length=255)),
                ('base_url', models.CharField(default='https://api.sandbox.co.in', max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('outlet', models.ForeignKey(blank=True, help_text='Null for global config', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.outlet')),
            ],
            options={
                'db_table': 'core_sandboxconfiguration',
                'ordering': ['-created_at'],
            },
        ),
    ]
