# Generated by Django 5.0.3 on 2026-08-12 18:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_sandboxconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='GstTaxpayerAuth',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gstin', models.CharField(help_text='Mirror of outlet.gstin', max_length=15)),
                ('gst_username', models.CharField(max_length=50)),
                ('_session_token_encrypted', models.TextField(blank=True, default='')),
                ('session_expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_otp_requested_at', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('outlet', models.OneToOneField(help_text='One auth record per Outlet', on_delete=django.db.models.deletion.CASCADE, to='core.outlet')),
            ],
            options={
                'db_table': 'core_gsttaxpayerauth',
            },
        ),
    ]
