# Generated by Django 5.0.3 on 2026-08-13 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_gsttaxpayerauth'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlet',
            name='gst_username',
            field=models.CharField(blank=True, help_text='GST portal username for API access', max_length=50),
        ),
    ]
