# Generated by Django 5.0.3 on 2026-08-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_outlet_gst_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='outletsettings',
            name='gstr2b_tolerance',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Tolerance for GSTR-2B reconciliation in INR', max_digits=5),
        ),
    ]
