# Generated by Django 5.0.3 on 2026-09-29 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_outletsettings_gstr2b_tolerance'),
    ]

    operations = [
        migrations.AddField(
            model_name='sandboxconfiguration',
            name='_einvoice_password_encrypted',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='sandboxconfiguration',
            name='_einvoice_username_encrypted',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
