# Generated by Django 5.0.3 on 2026-09-24 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_outletsettings_gstr2b_tolerance'),
    ]

    operations = [
        migrations.AddField(
            model_name='outletsettings',
            name='allowed_attendance_ips',
            field=models.TextField(blank=True, default='', help_text='Comma-separated list of allowed public IP addresses for Wi-Fi attendance check-in.'),
        ),
        migrations.AddField(
            model_name='outletsettings',
            name='attendance_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='GPS Latitude for geofenced attendance.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='outletsettings',
            name='attendance_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='GPS Longitude for geofenced attendance.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='outletsettings',
            name='attendance_radius_meters',
            field=models.IntegerField(default=100, help_text='Allowed radius in meters around the GPS coordinates.'),
        ),
    ]
