# Generated by Django 5.0.3 on 2026-10-02 11:43

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_sandboxconfiguration__einvoice_password_encrypted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outletsettings',
            name='print_settings_retail',
            field=models.JSONField(blank=True, default=apps.core.models.default_print_settings_retail),
        ),
        migrations.AddField(
            model_name='outletsettings',
            name='print_settings_wholesale',
            field=models.JSONField(blank=True, default=apps.core.models.default_print_settings_wholesale),
        ),
    ]
