# Generated by Django 5.0.3 on 2026-10-03 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_outletsettings_allowed_attendance_ips_and_more'),
        ('core', '0011_outletsettings_print_settings_retail_and_more'),
    ]

    operations = [
    ]
