# Generated by Django 5.0.3 on 2026-10-03 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_outletsettings_print_settings_retail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outletsettings',
            name='enable_einvoice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='outletsettings',
            name='enable_eway_bill',
            field=models.BooleanField(default=False),
        ),
    ]
