# Generated by Django 5.0.3 on 2026-10-09 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_merge_20261003_1403'),
        ('core', '0012_outletsettings_enable_einvoice_and_more'),
    ]

    operations = [
    ]
