# Generated by Django 5.0.3 on 2026-07-30 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0006_gstin_outlet_unique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseitem',
            name='sale_rate',
        ),
    ]
