# Generated by Django 5.0.3 on 2026-07-30 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0007_remove_purchaseitem_sale_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='gst_per_unit',
            field=models.DecimalField(decimal_places=4, default=0, help_text='GST amount apportioned per unit', max_digits=10),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='landing_rate',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Landing rate per unit', max_digits=10),
        ),
    ]
