# Generated by Django 5.0.3 on 2026-08-14 16:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0008_purchaseitem_gst_per_unit_purchaseitem_landing_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule37Adjustment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PROPOSED', 'Proposed'), ('APPROVED', 'Approved'), ('INCLUDED_IN_EXPORT', 'Included in Export')], default='PROPOSED', max_length=20)),
                ('action_type', models.CharField(choices=[('REVERSAL_DUE', 'Reversal Due (Unpaid > 180 Days)'), ('REAVAILMENT_ELIGIBLE', 'Re-availment Eligible (Subsequent Payment)')], max_length=30)),
                ('rule37_due_date', models.DateField(help_text='invoice_date + 180 days')),
                ('days_outstanding_at_evaluation', models.IntegerField()),
                ('calculation_date', models.DateTimeField(auto_now_add=True)),
                ('invoice_total_at_evaluation', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_paid_at_evaluation', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unpaid_amount_at_evaluation', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unpaid_ratio', models.DecimalField(decimal_places=4, help_text='Proportion of unpaid invoice value (0.0 to 1.0)', max_digits=5)),
                ('reversed_igst', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reversed_cgst', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reversed_sgst', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reversed_cess', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gstr_reason_code', models.CharField(default='RULE_37', max_length=50)),
                ('target_gstr3b_table', models.CharField(default='4(B)(2)', max_length=50)),
                ('metadata', models.JSONField(default=dict, help_text='Immutable calculation metadata/payment references')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule37_adjustments', to='purchases.purchaseinvoice')),
                ('source_reversal', models.ForeignKey(blank=True, help_text='Links a REAVAILMENT_ELIGIBLE back to its REVERSAL_DUE', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reavailments', to='purchases.rule37adjustment')),
            ],
            options={
                'db_table': 'purchases_rule37adjustment',
                'ordering': ['-calculation_date'],
            },
        ),
    ]
