# Generated by Django 5.0.3 on 2026-08-15 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0009_rule37adjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule37adjustment',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rule37adjustment',
            name='reclaim_period',
            field=models.CharField(blank=True, help_text='Format: MMYYYY', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='rule37adjustment',
            name='reclaimed_cgst',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='rule37adjustment',
            name='reclaimed_igst',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='rule37adjustment',
            name='reclaimed_sgst',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='rule37adjustment',
            name='status',
            field=models.CharField(choices=[('PROPOSED', 'Proposed'), ('NEEDS_REVIEW', 'Needs Review (Missing Allocation)'), ('APPROVED', 'Approved'), ('INCLUDED_IN_EXPORT', 'Included in Export')], default='PROPOSED', max_length=20),
        ),
    ]
