# Generated by Django 5.0.3 on 2026-10-04 23:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_outletsettings_enable_einvoice_and_more'),
        ('inventory', '0025_masterproduct_preferred_distributor'),
        ('purchases', '0010_rule37adjustment_payment_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('po_number', models.CharField(help_text='Auto-generated PO number', max_length=50)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('PARTIAL', 'Partially Received'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, help_text='Estimated total cost', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='purchases.distributor')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='core.outlet')),
            ],
            options={
                'db_table': 'purchases_purchaseorder',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qty_strips', models.IntegerField(default=1, help_text='Quantity ordered in strips/packs')),
                ('unit_ptr_estimated', models.DecimalField(decimal_places=2, default=0, help_text='Estimated PTR per pack', max_digits=10)),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=0, help_text='Estimated amount', max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='po_items', to='inventory.masterproduct')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchases.purchaseorder')),
            ],
            options={
                'db_table': 'purchases_purchaseorderitem',
            },
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['outlet', 'status'], name='purchases_p_outlet__a0cab8_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['po_number'], name='purchases_p_po_numb_ba9e90_idx'),
        ),
    ]
