# Generated by Django 5.0.3 on 2026-10-03 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_merge_20261003_1403'),
        ('purchases', '0010_rule37adjustment_payment_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='distributor',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='purchaseinvoice',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='distributor',
            name='contact_person',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='distributor',
            name='dl_no_20b',
            field=models.CharField(blank=True, help_text='Drug Licence 20B number (retail)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='distributor',
            name='dl_no_21b',
            field=models.CharField(blank=True, help_text='Drug Licence 21B number (wholesale)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='distributor',
            name='mobile',
            field=models.CharField(blank=True, help_text='Mobile number for 3-tier OCR matching', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='distributor',
            name='ocr_column_map',
            field=models.JSONField(blank=True, default=dict, help_text='Learned column header synonyms for this distributor'),
        ),
        migrations.AddField(
            model_name='distributor',
            name='state_code',
            field=models.CharField(blank=True, help_text='GST state code e.g. 27 for Maharashtra', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='invoice_image',
            field=models.ImageField(blank=True, help_text='Scanned invoice photo', null=True, upload_to='purchase_invoices/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='ocr_confidence',
            field=models.FloatField(blank=True, help_text='Overall OCR confidence score 0-1', null=True),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='ocr_distributor_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='ocr_distributor_dl',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='ocr_distributor_gstin',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='ocr_distributor_name',
            field=models.CharField(blank=True, help_text='Distributor name as read from invoice', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='ocr_distributor_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='ocr_processing_error',
            field=models.TextField(blank=True, help_text='Error message if OCR processing failed', null=True),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='ocr_raw_data',
            field=models.JSONField(blank=True, help_text='OCR extracted data: header, items, totals', null=True),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft — Scanned, pending human review'), ('POSTED', 'Posted — Confirmed, stock updated')], default='POSTED', help_text='DRAFT = OCR scan pending review; POSTED = confirmed & stock updated', max_length=10),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='drug_license_no',
            field=models.CharField(blank=True, help_text='Combined DL number for display', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='state',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='distributor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_invoices', to='purchases.distributor'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='invoice_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='invoice_no',
            field=models.CharField(blank=True, default='', help_text='Distributor invoice number', max_length=100),
        ),
        migrations.AddIndex(
            model_name='distributor',
            index=models.Index(fields=['outlet', 'name'], name='purchases_d_outlet__4f6e59_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseinvoice',
            index=models.Index(fields=['outlet', 'status'], name='purchases_p_outlet__ba9c59_idx'),
        ),
    ]
