# Generated by Django 5.0.3 on 2026-10-08 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0011_purchaseorder_purchaseorderitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='expected_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='purchase_bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_pos', to='purchases.purchaseinvoice'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='last_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='PTR at time of order', max_digits=10),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='received_qty',
            field=models.IntegerField(default=0, help_text='Quantity received so far'),
        ),
    ]
