# Generated by Django 5.0.3 on 2026-10-05 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0011_scan_purchase_draft_ocr_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='invoice_discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Invoice-level cash discount amount applied before GST', max_digits=12),
        ),
    ]
