# Generated by Django 5.0.3 on 2026-10-09 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0012_purchaseinvoice_invoice_discount'),
        ('purchases', '0013_alter_purchaseorder_status'),
    ]

    operations = [
    ]
