# Generated by Django 5.0.3 on 2026-06-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_customer_state_doctor_address_doctor_degree_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='can_edit_purchases',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staff',
            name='can_edit_sales',
            field=models.BooleanField(default=False),
        ),
    ]
