# Generated by Django 5.0.3 on 2026-07-05 10:36

from django.db import migrations, models


def backfill_granular_permissions(apps, schema_editor):
    Staff = apps.get_model('accounts', 'Staff')
    # Update users who have manager or admin roles
    Staff.objects.filter(role__in=['manager', 'admin', 'super_admin']).update(
        can_edit_sale_returns=True,
        can_edit_purchase_returns=True,
        can_edit_vouchers=True,
        can_view_audit_history=True,
        can_void_records=True
    )

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_staff_can_cancel_and_reissue_bill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='can_edit_purchase_returns',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staff',
            name='can_edit_sale_returns',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staff',
            name='can_edit_vouchers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staff',
            name='can_view_audit_history',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staff',
            name='can_void_records',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(backfill_granular_permissions),
    ]
