# Generated by Django 5.0.3 on 2026-07-05 10:44

from django.db import migrations, models


def backfill_post_settlement_permissions(apps, schema_editor):
    Staff = apps.get_model('accounts', 'Staff')
    # Update users who have manager or admin roles
    Staff.objects.filter(role__in=['manager', 'admin', 'super_admin']).update(
        can_modify_paid_purchases=True,
        can_modify_settled_vouchers=True,
        can_modify_settled_returns=True,
    )

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_staff_can_edit_purchase_returns_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='can_modify_paid_purchases',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staff',
            name='can_modify_settled_returns',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staff',
            name='can_modify_settled_vouchers',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(backfill_post_settlement_permissions),
    ]
