# Generated by Django 5.0.3 on 2026-07-09 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_staff_can_modify_paid_purchases_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('reversed', 'Reversed'), ('cancelled', 'Cancelled')], default='posted', max_length=20),
        ),
    ]
