# Generated by Django 5.0.3 on 2026-07-14 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_voucher_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='debitnote',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
