# Generated by Django 5.0.3 on 2026-09-03 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_voucher_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='can_export_gst',
            field=models.BooleanField(default=False),
        ),
    ]
