# Generated by Django 5.0.3 on 2026-09-21 22:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_customer_unique_together'),
        ('core', '0009_outletsettings_gstr2b_tolerance'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='can_manage_partners',
            field=models.BooleanField(default=False, help_text='Can manage profit split partners'),
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('profit_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Percentage of net profit (e.g., 35.00)', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='core.outlet')),
            ],
            options={
                'db_table': 'accounts_partner',
                'ordering': ['name'],
                'unique_together': {('outlet', 'name')},
            },
        ),
    ]
