# Generated by Django 5.0.3 on 2026-09-22 00:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_staff_can_manage_partners_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerShareHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profit_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_history', to='accounts.partner')),
            ],
            options={
                'db_table': 'accounts_partnersharehistory',
                'ordering': ['-start_date'],
            },
        ),
    ]
