# Generated by Django 5.0.3 on 2026-09-22 16:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_partnersharehistory'),
        ('billing', '0021_saleinvoice_billing_basis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='credit_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('RETAIL', 'Retail'), ('WHOLESALE', 'Wholesale')], default='RETAIL', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='dl_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='dl_no_20b',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='dl_no_21b',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_credit_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='pan',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='state_code',
            field=models.CharField(default='27', max_length=2),
        ),
        migrations.CreateModel(
            name='PostDatedCheque',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cheque_number', models.CharField(max_length=50)),
                ('bank_name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cheque_date', models.DateField()),
                ('deposit_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DEPOSITED', 'Deposited'), ('CLEARED', 'Cleared'), ('BOUNCED', 'Bounced'), ('RETURNED', 'Returned')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_dated_cheques', to='accounts.customer')),
                ('linked_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_pdcs', to='billing.saleinvoice')),
            ],
            options={
                'db_table': 'accounts_postdatedcheque',
                'ordering': ['cheque_date'],
            },
        ),
    ]
