# Generated by Django 5.0.3 on 2026-09-24 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_partnersharehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='shift_end_time',
            field=models.TimeField(blank=True, help_text='Specific shift end time. If null, falls back to outlet closing time.', null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='shift_start_time',
            field=models.TimeField(blank=True, help_text='Specific shift start time. If null, falls back to outlet opening time.', null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='weekly_off_day',
            field=models.IntegerField(blank=True, help_text='0=Monday, 6=Sunday. Null means no specific off day.', null=True),
        ),
    ]
