# Generated by Django 5.0.3 on 2026-10-03 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_customer_credit_days_customer_customer_type_and_more'),
        ('accounts', '0025_staff_shift_end_time_staff_shift_start_time_and_more'),
    ]

    operations = [
    ]
