# Generated by Django 5.0.3 on 2026-08-13 17:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0008_outlet_gst_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='GSTTransactionSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gstin', models.CharField(help_text='GSTIN of the taxpayer (Outlet) at the time of transaction', max_length=15)),
                ('period', models.CharField(help_text='Format: MMYYYY, e.g. 042025', max_length=6)),
                ('transaction_type', models.CharField(choices=[('sale', 'Sale'), ('purchase', 'Purchase'), ('sales_return', 'Sales Return'), ('purchase_return', 'Purchase Return')], max_length=20)),
                ('document_id', models.UUIDField(help_text='UUID of the source invoice/return')),
                ('document_number', models.CharField(help_text='Invoice or return number', max_length=50)),
                ('document_date', models.DateField()),
                ('snapshot_json', models.JSONField(help_text='Normalized GST payload (taxable values, igst, cgst, sgst, hsn splits)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gst_snapshots', to='core.outlet')),
            ],
            options={
                'db_table': 'reports_gsttransactionsnapshot',
                'ordering': ['-document_date', '-created_at'],
                'indexes': [models.Index(fields=['outlet', 'period', 'transaction_type'], name='reports_gst_outlet__318d33_idx'), models.Index(fields=['document_number'], name='reports_gst_documen_00ba2c_idx')],
            },
        ),
    ]
