# Generated by Django 5.0.3 on 2026-08-14 22:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_outlet_gst_username'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GSTR2BData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period', models.CharField(help_text='Format: MMYYYY, e.g. 042025', max_length=6)),
                ('supplier_gstin', models.CharField(max_length=15)),
                ('invoice_number', models.CharField(max_length=50)),
                ('invoice_date', models.DateField()),
                ('taxable_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('igst', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cgst', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sgst', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cess', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('supplier_status', models.CharField(default='Active', max_length=20)),
                ('raw_data', models.JSONField(default=dict)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.outlet')),
            ],
            options={
                'db_table': 'reports_gstr2bdata',
            },
        ),
        migrations.CreateModel(
            name='ITCReconciliationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period', models.CharField(help_text='Format: MMYYYY', max_length=6)),
                ('run_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=20)),
                ('summary', models.JSONField(default=dict)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.outlet')),
            ],
            options={
                'db_table': 'reports_itcreconciliationrun',
            },
        ),
        migrations.CreateModel(
            name='ITCReconciliationResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('match_status', models.CharField(max_length=30)),
                ('mismatch_reasons', models.JSONField(default=list)),
                ('gstr2b_record', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.gstr2bdata')),
                ('purchase_snapshot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.gsttransactionsnapshot')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='reports.itcreconciliationrun')),
            ],
            options={
                'db_table': 'reports_itcreconciliationresult',
            },
        ),
        migrations.AddIndex(
            model_name='gstr2bdata',
            index=models.Index(fields=['outlet', 'period', 'supplier_gstin'], name='reports_gst_outlet__2f05b7_idx'),
        ),
    ]
