# Generated by Django 5.0.3 on 2026-08-15 00:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0010_rule37adjustment_payment_date_and_more'),
        ('reports', '0002_gstr2bdata_itcreconciliationrun_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeferredITCEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_period', models.CharField(help_text='Format: MMYYYY', max_length=6)),
                ('iamt', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('camt', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('samt', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('csamt', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('DEFERRED', 'Deferred'), ('CLAIMED', 'Claimed'), ('WRITTEN_OFF', 'Written Off')], default='DEFERRED', max_length=20)),
                ('claimed_period', models.CharField(blank=True, help_text='Format: MMYYYY', max_length=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchase_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deferred_itc_entries', to='purchases.purchaseinvoice')),
            ],
            options={
                'db_table': 'reports_deferreditcentry',
                'unique_together': {('purchase_invoice', 'original_period')},
            },
        ),
    ]
