# Generated by Django 5.0.3 on 2026-08-16 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_outlet_gst_username'),
        ('reports', '0003_deferreditcentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GSTExportAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(help_text='Format: MMYYYY', max_length=6)),
                ('export_type', models.CharField(choices=[('GSTR1_EXCEL', 'GSTR-1 Excel Utility'), ('WORKING_PAPER_PDF', 'CA Working Paper PDF'), ('RECONCILIATION_EXCEL', 'Reconciliation Workbook')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('template_checksum', models.CharField(blank=True, max_length=64, null=True)),
                ('template_version', models.CharField(blank=True, max_length=50, null=True)),
                ('source_json_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('output_file_hash', models.CharField(max_length=64)),
                ('validation_state', models.JSONField(default=dict)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gst_exports', to=settings.AUTH_USER_MODEL)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.outlet')),
            ],
            options={
                'db_table': 'reports_gstexportaudit',
                'ordering': ['-timestamp'],
            },
        ),
    ]
