# Generated by Django 5.0.3 on 2026-08-20 17:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_outlet_gst_username'),
        ('reports', '0004_gstexportaudit'),
    ]

    operations = [
        migrations.AddField(
            model_name='gstr2bdata',
            name='document_type',
            field=models.CharField(blank=True, choices=[('B2B', 'B2B'), ('B2BA', 'B2BA'), ('CDN', 'CDN'), ('CDNA', 'CDNA'), ('ISD', 'ISD')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='gstr2bdata',
            name='ims_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='gstr2bdata',
            name='itc_availability_status',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='gstr2bdata',
            name='itc_ineligible_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gstr2bdata',
            name='original_document_reference',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='gstr2bdata',
            name='supplier_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gstexportaudit',
            name='export_type',
            field=models.CharField(choices=[('GSTR1_EXCEL', 'GSTR-1 Excel Utility'), ('GSTR3B_OFFLINE_UTILITY', 'GSTR-3B Offline Utility'), ('WORKING_PAPER_PDF', 'CA Working Paper PDF'), ('RECONCILIATION_EXCEL', 'Reconciliation Workbook')], max_length=50),
        ),
        migrations.CreateModel(
            name='GSTR2BImportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gstin', models.CharField(max_length=15)),
                ('period', models.CharField(help_text='Format: MMYYYY', max_length=6)),
                ('provider', models.CharField(default='Sandbox', max_length=50)),
                ('retrieval_timestamp', models.DateTimeField(auto_now_add=True)),
                ('session_reference_id', models.UUIDField(blank=True, null=True)),
                ('provider_chksum', models.CharField(blank=True, max_length=64, null=True)),
                ('local_payload_sha256', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(max_length=30)),
                ('file_count_expected', models.IntegerField(default=1)),
                ('file_count_fetched', models.IntegerField(default=0)),
                ('record_count', models.IntegerField(default=0)),
                ('error_metadata', models.JSONField(blank=True, default=dict)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gstr2b_jobs', to='core.outlet')),
                ('reused_from_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.gstr2bimportjob')),
            ],
            options={
                'db_table': 'reports_gstr2bimportjob',
            },
        ),
        migrations.AddField(
            model_name='gstr2bdata',
            name='import_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='reports.gstr2bimportjob'),
        ),
        migrations.AddField(
            model_name='itcreconciliationrun',
            name='import_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.gstr2bimportjob'),
        ),
        migrations.AlterUniqueTogether(
            name='gstr2bdata',
            unique_together={('import_job', 'supplier_gstin', 'document_type', 'invoice_number')},
        ),
        migrations.AddIndex(
            model_name='gstr2bimportjob',
            index=models.Index(fields=['outlet', 'period', 'gstin'], name='reports_gst_outlet__ef175f_idx'),
        ),
    ]
