# Generated by Django 5.0.3 on 2026-08-21 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_gstr2bdata_document_type_gstr2bdata_ims_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gstr2bdata',
            name='normalizer_version',
            field=models.CharField(default='1.0', max_length=20),
        ),
        migrations.AddField(
            model_name='gstr2bdata',
            name='raw_record_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='gstr2bdata',
            name='source_document_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='gstr2bdata',
            name='source_field_map',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='gstr2bimportjob',
            name='host',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gstr2bimportjob',
            name='page_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='gstr2bimportjob',
            name='provider_mode',
            field=models.CharField(default='test', max_length=20),
        ),
        migrations.AddField(
            model_name='gstr2bimportjob',
            name='raw_payload_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='gstr2bimportjob',
            name='request_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
