# Generated by Django 5.0.3 on 2026-08-21 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_gstr2bdata_normalizer_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gsttransactionsnapshot',
            name='transaction_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('purchase', 'Purchase'), ('sales_return', 'Sales Return'), ('purchase_return', 'Purchase Return'), ('sales_credit_note', 'Sales Credit Note'), ('sales_debit_note', 'Sales Debit Note'), ('purchase_credit_note', 'Purchase Credit Note'), ('purchase_debit_note', 'Purchase Debit Note')], max_length=20),
        ),
    ]
