# Generated by Django 5.0.3 on 2026-08-27 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_alter_gsttransactionsnapshot_transaction_type'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='itcreconciliationresult',
            index=models.Index(fields=['run', 'match_status'], name='reports_itc_run_id_4dc9bf_idx'),
        ),
        migrations.AddIndex(
            model_name='itcreconciliationresult',
            index=models.Index(fields=['purchase_snapshot', 'gstr2b_record'], name='reports_itc_purchas_89cabd_idx'),
        ),
    ]
