# Generated by Django 5.0.3 on 2026-09-21 23:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_outletsettings_gstr2b_tolerance'),
        ('reports', '0008_itcreconciliationresult_reports_itc_run_id_4dc9bf_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCashReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('notes_2000', models.IntegerField(default=0)),
                ('notes_500', models.IntegerField(default=0)),
                ('notes_200', models.IntegerField(default=0)),
                ('notes_100', models.IntegerField(default=0)),
                ('notes_50', models.IntegerField(default=0)),
                ('notes_20', models.IntegerField(default=0)),
                ('notes_10', models.IntegerField(default=0)),
                ('carton_sale', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('petty_cash_exp', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('side_cash', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('next_day_opening', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_cash_reports', to='core.outlet')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reports_dailycashreport',
                'ordering': ['-date'],
                'unique_together': {('outlet', 'date')},
            },
        ),
        migrations.CreateModel(
            name='FixedMonthlyExpense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('transport', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('petrol', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('light', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('water', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('internet', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stationery', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('int_on_cc', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('income_tax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ca_fees', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('godown', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('other', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('days_in_month', models.IntegerField(default=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_monthly_expenses', to='core.outlet')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reports_fixedmonthlyexpense',
                'unique_together': {('outlet',)},
            },
        ),
    ]
