'use client';

import { useState, useEffect } from 'react';
import { gstApi } from '@/lib/apiClient';
import { Skeleton } from '@/components/ui/skeleton';
import { useToast } from '@/hooks/use-toast';
import { format } from 'date-fns';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { ChevronLeft, ChevronRight } from 'lucide-react';

export default function HistoryPage() {
    const [audits, setAudits] = useState<any[]>([]);
    const [loading, setLoading] = useState(true);
    const [page, setPage] = useState(1);
    const [hasMore, setHasMore] = useState(false);
    const { toast } = useToast();

    useEffect(() => {
        loadHistory(page);
    }, [page]);

    const loadHistory = async (p: number) => {
        setLoading(true);
        try {
            const data = await gstApi.getAuditHistory(p);
            setAudits(data.results || []);
            setHasMore(!!data.next);
        } catch (error) {
            console.error("Failed to load export history", error);
            toast({ variant: 'destructive', title: 'Failed to load export history' });
        } finally {
            setLoading(false);
        }
    };

    return (
        <div className="space-y-6 max-w-7xl mx-auto pb-12">
            <div>
                <h1 className="text-2xl font-bold text-slate-900">Export History & Audit Logs</h1>
                <p className="text-sm text-slate-500">Track all generated GST returns and Offline Tool utilities.</p>
            </div>

            <div className="bg-white rounded-lg shadow-sm border overflow-hidden">
                <div className="overflow-x-auto">
                    <table className="w-full text-sm text-left">
                        <thead className="bg-slate-50 text-slate-500 border-b">
                            <tr>
                                <th className="px-6 py-3 font-medium">Timestamp</th>
                                <th className="px-6 py-3 font-medium">Period</th>
                                <th className="px-6 py-3 font-medium">Export Type</th>
                                <th className="px-6 py-3 font-medium">Status</th>
                                <th className="px-6 py-3 font-medium">Generated By</th>
                                <th className="px-6 py-3 font-medium">Version</th>
                            </tr>
                        </thead>
                        <tbody className="divide-y divide-slate-100">
                            {loading && audits.length === 0 ? (
                                <tr>
                                    <td colSpan={6} className="px-6 py-8 text-center">
                                        <Skeleton className="w-full h-8 mb-2" />
                                        <Skeleton className="w-full h-8 mb-2" />
                                        <Skeleton className="w-full h-8" />
                                    </td>
                                </tr>
                            ) : audits.length === 0 ? (
                                <tr>
                                    <td colSpan={6} className="px-6 py-8 text-center text-slate-500">
                                        No export history found.
                                    </td>
                                </tr>
                            ) : (
                                audits.map((audit) => (
                                    <tr key={audit.id} className="hover:bg-slate-50">
                                        <td className="px-6 py-4 whitespace-nowrap">
                                            {format(new Date(audit.timestamp), 'PP pp')}
                                        </td>
                                        <td className="px-6 py-4">
                                            {audit.period}
                                        </td>
                                        <td className="px-6 py-4 font-medium text-slate-900">
                                            {audit.export_type_display || audit.export_type}
                                        </td>
                                        <td className="px-6 py-4">
                                            <Badge variant={audit.status === 'Generated' ? 'default' : 'destructive'}>
                                                {audit.status}
                                            </Badge>
                                        </td>
                                        <td className="px-6 py-4">
                                            {audit.generated_by}
                                        </td>
                                        <td className="px-6 py-4 text-xs text-slate-500">
                                            {audit.template_version || 'N/A'}
                                        </td>
                                    </tr>
                                ))
                            )}
                        </tbody>
                    </table>
                </div>
                
                <div className="flex items-center justify-between px-6 py-3 border-t bg-slate-50">
                    <Button 
                        variant="outline" 
                        size="sm" 
                        disabled={page === 1}
                        onClick={() => setPage(p => p - 1)}
                    >
                        <ChevronLeft className="w-4 h-4 mr-1" /> Previous
                    </Button>
                    <span className="text-sm text-slate-500">Page {page}</span>
                    <Button 
                        variant="outline" 
                        size="sm" 
                        disabled={!hasMore}
                        onClick={() => setPage(p => p + 1)}
                    >
                        Next <ChevronRight className="w-4 h-4 ml-1" />
                    </Button>
                </div>
            </div>
        </div>
    );
}
