# Generated by Django 5.0.3 on 2026-05-06 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_batch_opening_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='pack_size',
            field=models.IntegerField(default=1, help_text='Number of units per pack (e.g., 10 tablets per strip)'),
        ),
        migrations.AddField(
            model_name='batch',
            name='pack_type',
            field=models.CharField(choices=[('strip', 'Strip'), ('bottle', 'Bottle'), ('vial', 'Vial'), ('box', 'Box'), ('blister', 'Blister'), ('tube', 'Tube'), ('packet', 'Packet'), ('other', 'Other')], default='strip', max_length=20),
        ),
        migrations.AddField(
            model_name='batch',
            name='pack_unit',
            field=models.CharField(default='tablet', help_text='Unit name (e.g., tablet, capsule, ml, etc.)', max_length=50),
        ),
    ]
