# Generated by Django 5.0.3 on 2026-05-06 16:57

from django.db import migrations


def copy_pack_sizes(apps, schema_editor):
    Batch = apps.get_model('inventory', 'Batch')
    for batch in Batch.objects.select_related('product').all():
        if batch.product:
            batch.pack_size = batch.product.pack_size
            batch.pack_unit = batch.product.pack_unit
            batch.pack_type = batch.product.pack_type
            batch.save(update_fields=['pack_size', 'pack_unit', 'pack_type'])

def reverse_copy(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_batch_pack_size_batch_pack_type_batch_pack_unit'),
    ]

    operations = [
        migrations.RunPython(copy_pack_sizes, reverse_copy),
    ]
