# Generated by Django 5.0.3 on 2026-06-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_inventory_search_performance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterproduct',
            name='drug_type',
            field=models.CharField(choices=[('allopathy', 'Allopathy'), ('ayurveda', 'Ayurveda'), ('homeo', 'Homeopathy'), ('surgical', 'Surgical / Device'), ('general', 'General / FMCG'), ('fmcg', 'FMCG')], max_length=20),
        ),
    ]
