# Generated by Django 5.0.3 on 2026-07-30 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_alter_masterproduct_drug_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='sale_rate',
        ),
        migrations.RemoveField(
            model_name='masterproduct',
            name='default_sale_rate',
        ),
    ]
