# Generated by Django 5.0.3 on 2026-08-02 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_remove_batch_sale_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockledger',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_ledger_entries', to='inventory.masterproduct'),
        ),
    ]
