# Generated by Django 5.0.3 on 2026-08-06 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_batch_pack_type_cleanup'),
        ('inventory', '0017_stockledger_actor'),
    ]

    operations = [
    ]
