# Generated by Django 5.0.3 on 2026-08-14 15:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_outlet_gst_username'),
        ('inventory', '0018_merge_20260806_1213'),
        ('purchases', '0008_purchaseitem_gst_per_unit_purchaseitem_landing_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('adjustment_type', models.CharField(choices=[('EXPIRED', 'Expired'), ('DAMAGED', 'Damaged'), ('DESTROYED', 'Destroyed'), ('THEFT_LOSS', 'Theft/Loss')], max_length=50)),
                ('qty_strips', models.IntegerField(default=0)),
                ('qty_loose', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('PROPOSED', 'Proposed'), ('APPROVED', 'Approved'), ('INCLUDED_IN_EXPORT', 'Included in Export')], default='PROPOSED', max_length=50)),
                ('traceability_status', models.CharField(choices=[('FIFO_MATCHED', 'FIFO Matched'), ('NEEDS_REVIEW', 'Needs Review')], default='NEEDS_REVIEW', max_length=50)),
                ('reason', models.TextField(blank=True, null=True)),
                ('effective_date', models.DateField()),
                ('gstr_reason_code', models.CharField(default='SECTION_17_5_H', max_length=50)),
                ('target_gstr3b_table', models.CharField(default='4(B)(1)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_adjustments', to='inventory.batch')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_adjustments', to='core.outlet')),
            ],
        ),
        migrations.CreateModel(
            name='StockAdjustmentAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('allocated_qty', models.DecimalField(decimal_places=3, max_digits=12)),
                ('taxable_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('reversed_igst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('reversed_cgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('reversed_sgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('reversed_cess_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('allocation_order', models.IntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_purchase_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustment_allocations', to='purchases.purchaseitem')),
                ('stock_adjustment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='inventory.stockadjustment')),
            ],
            options={
                'ordering': ['allocation_order'],
            },
        ),
    ]
