# Generated by Django 5.0.3 on 2026-08-14 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_stockadjustment_stockadjustmentallocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockadjustment',
            name='source_ledger_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_adjustment', to='inventory.stockledger'),
        ),
    ]
