# Generated by Django 5.0.3 on 2026-08-30 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_stockadjustment_source_ledger_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='landing_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Landing cost per pack', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='stockledger',
            name='qty_in',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='stockledger',
            name='qty_out',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='stockledger',
            name='running_qty',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
    ]
