# Generated by Django 5.0.3 on 2026-09-22 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_batch_landing_rate_alter_stockledger_qty_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='default_scheme',
            field=models.CharField(blank=True, help_text='Default scheme, e.g., 10+1', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='ptr',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price to Retailer', max_digits=10),
        ),
        migrations.AddField(
            model_name='batch',
            name='pts',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price to Stockist', max_digits=10),
        ),
    ]
