# Generated by Django 5.0.3 on 2026-09-22 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_outletsettings_gstr2b_tolerance'),
        ('inventory', '0022_batch_default_scheme_batch_ptr_batch_pts'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['product_id', 'expiry_date', 'ptr'], name='inventory_b_product_57baca_idx'),
        ),
    ]
