# Generated by Django 5.0.3 on 2026-10-04 15:53

import django.contrib.postgres.indexes
from django.contrib.postgres.operations import TrigramExtension, BtreeGinExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_batch_inventory_b_product_57baca_idx'),
    ]

    operations = [
        TrigramExtension(),
        BtreeGinExtension(),
        migrations.AddIndex(
            model_name='masterproduct',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='master_prod_name_trgm_gin', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='masterproduct',
            index=django.contrib.postgres.indexes.GinIndex(fields=['composition'], name='master_prod_comp_trgm_gin', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='masterproduct',
            index=django.contrib.postgres.indexes.GinIndex(fields=['manufacturer'], name='master_prod_mfg_trgm_gin', opclasses=['gin_trgm_ops']),
        ),
    ]
