# Generated by Django 5.0.3 on 2026-10-03 16:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_merge_20261003_1403'),
        ('inventory', '0023_batch_inventory_b_product_57baca_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterProductAlias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alias_name', models.CharField(db_index=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_aliases', to='core.outlet')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='inventory.masterproduct')),
            ],
            options={
                'db_table': 'inventory_masterproductalias',
                'unique_together': {('outlet', 'alias_name')},
            },
        ),
    ]
