# Generated by Django 5.0.3 on 2026-10-04 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_masterproduct_master_prod_name_trgm_gin_and_more'),
        ('purchases', '0010_rule37adjustment_payment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterproduct',
            name='preferred_distributor',
            field=models.ForeignKey(blank=True, help_text='Default distributor for reorder generation', null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchases.distributor'),
        ),
    ]
