# Generated by Django 5.0.3 on 2026-10-04 23:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_outletsettings_enable_einvoice_and_more'),
        ('inventory', '0025_masterproduct_preferred_distributor'),
        ('purchases', '0011_purchaseorder_purchaseorderitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterproduct',
            name='min_qty',
        ),
        migrations.RemoveField(
            model_name='masterproduct',
            name='preferred_distributor',
        ),
        migrations.RemoveField(
            model_name='masterproduct',
            name='reorder_qty',
        ),
        migrations.CreateModel(
            name='OutletProductConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('min_qty', models.DecimalField(decimal_places=2, default=0, help_text='Low-stock threshold in strips', max_digits=10)),
                ('reorder_qty', models.DecimalField(decimal_places=2, default=0, help_text='Suggested reorder quantity', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_configs', to='core.outlet')),
                ('preferred_distributor', models.ForeignKey(blank=True, help_text='Default distributor for reorder generation', null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchases.distributor')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outlet_configs', to='inventory.masterproduct')),
            ],
            options={
                'db_table': 'inventory_outletproductconfig',
                'indexes': [models.Index(fields=['outlet', 'product'], name='inventory_o_outlet__3ff29a_idx')],
                'unique_together': {('outlet', 'product')},
            },
        ),
    ]
