# Generated by Django 5.0.3 on 2026-10-08 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_remove_masterproduct_min_qty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outletproductconfig',
            name='preferred_distributor',
        ),
    ]
