# Generated by Django 5.0.3 on 2026-10-09 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_masterproductalias'),
        ('inventory', '0027_remove_outletproductconfig_preferred_distributor'),
    ]

    operations = [
    ]
