# Generated by Django 5.0.3 on 2026-06-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_alter_saleitem_qty_returned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='sale_mode',
            field=models.CharField(choices=[('strip', 'Strip'), ('loose', 'Loose'), ('bottle', 'Bottle'), ('mixed', 'Mixed')], default='strip', max_length=20),
        ),
    ]
