# Generated by Django 5.0.3 on 2026-06-22 18:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_staff_can_cancel_and_reissue_bill_and_more'),
        ('billing', '0010_saleinvoice_cancellation_reason_and_more'),
        ('core', '0005_outletsettings_landing_cost_include_freight_and_more'),
        ('inventory', '0014_alter_masterproduct_drug_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('draft_status', models.CharField(choices=[('draft', 'Draft'), ('held', 'Held')], default='draft', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('extra_discount_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('igst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('round_off', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_mode', models.CharField(default='cash', max_length=20)),
                ('schedule_h_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customer')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.doctor')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_invoices', to='core.outlet')),
            ],
            options={
                'db_table': 'billing_draftinvoice',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DraftInvoiceItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qty_strips', models.IntegerField(default=0)),
                ('qty_loose', models.IntegerField(default=0)),
                ('discount_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.batch')),
                ('draft_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.draftinvoice')),
            ],
            options={
                'db_table': 'billing_draftinvoiceitem',
            },
        ),
    ]
