# Generated by Django 5.0.3 on 2026-06-24 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_draftinvoice_draftinvoiceitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftinvoice',
            name='hospital_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='hospital_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
