# Generated by Django 5.0.3 on 2026-06-24 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_draftinvoice_hospital_name_saleinvoice_hospital_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftinvoice',
            name='prescription_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='prescription_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
