# Generated by Django 5.0.3 on 2026-07-04 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0014_quotation_quotationitem_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BillRevision',
        ),
    ]
