# Generated by Django 5.0.3 on 2026-07-07 15:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0015_delete_billrevision'),
        ('core', '0005_outletsettings_landing_cost_include_freight_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='salesreturn',
            constraint=models.UniqueConstraint(fields=('original_sale',), name='unique_sale_return_per_invoice'),
        ),
    ]
