# Generated by Django 5.0.3 on 2026-07-14 12:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0017_creditaccount_updated_at_and_more'),
        ('core', '0005_outletsettings_landing_cost_include_freight_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision_number', models.CharField(help_text='e.g., INV-2026-00123-R1', max_length=50)),
                ('revision_type', models.CharField(choices=[('correction', 'Correction (No financial impact)'), ('financial_change', 'Financial Change (Rates, Qty, Items)'), ('cancel_reissue', 'Cancel & Reissue')], max_length=50)),
                ('revision_status', models.CharField(choices=[('draft', 'Draft / Pending'), ('applied', 'Applied / Completed'), ('failed', 'Failed')], default='applied', max_length=50)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('reason_code', models.CharField(help_text='Standardized reason code', max_length=50)),
                ('reason_text', models.TextField(help_text='Detailed reason or notes provided by the staff')),
                ('old_snapshot_json', models.JSONField(default=dict, help_text='State of the invoice before modification')),
                ('new_snapshot_json', models.JSONField(default=dict, help_text='Proposed or applied corrected state')),
                ('diff_summary_json', models.JSONField(default=dict, help_text='Computed differences between old and new')),
                ('stock_impact_json', models.JSONField(default=dict, help_text='Summary of items added/removed back to stock')),
                ('payment_impact_json', models.JSONField(default=dict, help_text='Summary of cash/credit adjustments')),
                ('return_impact_json', models.JSONField(default=dict, help_text='Any automatic sales returns generated')),
                ('resulting_invoice_id', models.UUIDField(blank=True, help_text='If cancel/reissue, the ID of the new invoice', null=True)),
                ('linked_credit_note_id', models.UUIDField(blank=True, help_text='Linked credit note if financial values decreased', null=True)),
                ('linked_debit_note_id', models.UUIDField(blank=True, help_text='Linked debit note if financial values increased', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'billing_billrevision',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='salesreturn',
            name='unique_sale_return_per_invoice',
        ),
        migrations.RemoveField(
            model_name='creditaccount',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='credittransaction',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='expenseentry',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='ledgerentry',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='notificationlog',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='paymentallocation',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='paymententry',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='receiptallocation',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='receiptentry',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='saleinvoice',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='schedulehregister',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='billrevision',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_revisions_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='billrevision',
            name='original_invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='billing.saleinvoice'),
        ),
        migrations.AddField(
            model_name='billrevision',
            name='outlet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_revisions', to='core.outlet'),
        ),
        migrations.AddIndex(
            model_name='billrevision',
            index=models.Index(fields=['outlet', 'original_invoice'], name='billing_bil_outlet__4dd59e_idx'),
        ),
        migrations.AddIndex(
            model_name='billrevision',
            index=models.Index(fields=['revision_number', 'outlet'], name='billing_bil_revisio_757b20_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='billrevision',
            unique_together={('outlet', 'revision_number')},
        ),
    ]
