# Generated by Django 5.0.3 on 2026-08-02 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0018_billrevision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='hsn_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='qty_returned_loose',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='qty_returned_strips',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salesreturnitem',
            name='qty_returned_loose',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salesreturnitem',
            name='qty_returned_strips',
            field=models.IntegerField(default=0),
        ),
    ]
