# Generated by Django 5.0.3 on 2026-08-14 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0019_saleitem_hsn_code_saleitem_qty_returned_loose_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesreturn',
            name='manual_override',
            field=models.BooleanField(default=False, help_text='True if created without linking to an original invoice'),
        ),
        migrations.AlterField(
            model_name='salesreturn',
            name='original_sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='billing.saleinvoice'),
        ),
        migrations.AlterField(
            model_name='salesreturnitem',
            name='original_sale_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='return_items', to='billing.saleitem'),
        ),
    ]
