# Generated by Django 5.0.3 on 2026-09-22 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0020_salesreturn_manual_override_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleinvoice',
            name='billing_basis',
            field=models.CharField(choices=[('MRP', 'MRP'), ('PTR', 'PTR'), ('PTS', 'PTS')], default='MRP', max_length=20),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='cash_discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='cash_discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='eway_bill_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='irn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='is_interstate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='place_of_supply',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='sale_type',
            field=models.CharField(choices=[('RETAIL', 'Retail'), ('WHOLESALE', 'Wholesale')], default='RETAIL', max_length=20),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='total_free_loose',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='total_free_strips',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='cgst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='cgst_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='free_qty_loose',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='free_qty_strips',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='igst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='igst_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='sgst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='sgst_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='trade_discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='trade_discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='unit_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
