# Generated by Django 5.0.3 on 2026-09-23 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0021_saleinvoice_billing_basis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleinvoice',
            name='ack_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='ack_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='irn_status',
            field=models.CharField(choices=[('NOT_REQUIRED', 'Not Required'), ('PENDING', 'Pending'), ('GENERATED', 'Generated'), ('FAILED', 'Failed')], default='NOT_REQUIRED', max_length=20),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='qr_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='transporter_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='vehicle_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
