# Generated by Django 5.0.3 on 2026-10-01 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0022_saleinvoice_ack_date_saleinvoice_ack_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='billing_basis',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='is_interstate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quotation',
            name='place_of_supply',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='sale_type',
            field=models.CharField(default='RETAIL', max_length=20),
        ),
        migrations.AddField(
            model_name='quotation',
            name='transporter_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='vehicle_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='free_qty_loose',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='free_qty_strips',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='hsn_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='ptr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='pts',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
