# Generated by Django 5.0.3 on 2026-10-02 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0023_quotation_billing_basis_quotation_is_interstate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleinvoice',
            name='eway_bill_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='eway_bill_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('GENERATED', 'Generated'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='trans_distance',
            field=models.IntegerField(default=0, help_text='Distance in KM'),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='trans_mode',
            field=models.IntegerField(default=1, help_text='1-Road, 2-Rail, 3-Air, 4-Ship'),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='valid_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='vehicle_type',
            field=models.CharField(default='R', help_text='R-Regular, O-ODC', max_length=1),
        ),
    ]
