from django.core.management.base import BaseCommand
from apps.accounts.models import Staff

class Command(BaseCommand):
    help = 'Prints the test credentials generated by seeder'

    def handle(self, *args, **kwargs):
        staff = Staff.objects.filter(phone='9999999999').first()
        if not staff:
            self.stdout.write(self.style.ERROR('Test user (9999999999) not found. Run python manage.py seeder first.'))
            return
            
        self.stdout.write(self.style.SUCCESS('--- Test User Credentials ---'))
        self.stdout.write(f'Phone: {staff.phone}')
        self.stdout.write(f'PIN/Password: Admin123')
        self.stdout.write(f'Role: {staff.get_role_display()}')
        
        if staff.outlet:
            self.stdout.write(f'Outlet: {staff.outlet.name} (Organization: {staff.outlet.organization.name})')
        else:
            self.stdout.write(self.style.WARNING('Outlet: None (Warning: User needs an outlet!)'))
