# Generated by Django 5.2.15 on 2026-06-09 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_outletsettings_landing_cost_include_freight_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('action', models.CharField(db_index=True, max_length=255)),
                ('module', models.CharField(db_index=True, max_length=255)),
                ('entity_type', models.CharField(blank=True, db_index=True, max_length=255)),
                ('entity_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('entity_label', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('changes_json', models.JSONField(blank=True, default=dict)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('endpoint', models.CharField(blank=True, max_length=512)),
                ('http_method', models.CharField(blank=True, max_length=20)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('outlet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='core.outlet')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['module', 'action'], name='audit_activ_module_fb8b98_idx'), models.Index(fields=['entity_type', 'entity_id'], name='audit_activ_entity__5a526e_idx'), models.Index(fields=['timestamp', 'outlet'], name='audit_activ_timesta_1743f2_idx')],
            },
        ),
    ]
