# Generated by Django 5.0.3

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_pg_trgm_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='ip_is_routable',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
