# Generated by Django 5.0.3 on 2026-06-24 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_activitylog_ip_is_routable'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='activitylog',
            name='audit_desc_gin_idx',
        ),
        migrations.RemoveIndex(
            model_name='activitylog',
            name='audit_label_gin_idx',
        ),
    ]
