# Generated by Django 5.0.3 on 2026-07-04 19:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_remove_activitylog_audit_desc_gin_idx_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0005_outletsettings_landing_cost_include_freight_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.UUIDField()),
                ('revision_number', models.CharField(help_text='e.g., INV-2026-00123-R1', max_length=50)),
                ('revision_type', models.CharField(choices=[('correction', 'Correction (No financial impact)'), ('financial_change', 'Financial Change (Rates, Qty, Items)'), ('cancel_reissue', 'Cancel & Reissue'), ('commercial_correction', 'Commercial Correction'), ('paid_bill_correction', 'Paid Bill Correction'), ('return_aware_correction', 'Return Aware Correction'), ('direct_revise', 'Direct Revise')], max_length=50)),
                ('revision_status', models.CharField(choices=[('draft', 'Draft / Pending'), ('applied', 'Applied / Completed'), ('failed', 'Failed')], default='applied', max_length=50)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('reason_code', models.CharField(blank=True, help_text='Standardized reason code', max_length=50)),
                ('reason_text', models.TextField(blank=True, help_text='Detailed reason or notes provided by the staff')),
                ('old_snapshot_json', models.JSONField(default=dict, help_text='State of the document before modification')),
                ('new_snapshot_json', models.JSONField(default=dict, help_text='Proposed or applied corrected state')),
                ('diff_summary_json', models.JSONField(default=dict, help_text='Computed differences between old and new')),
                ('stock_impact_json', models.JSONField(default=dict, help_text='Summary of items added/removed back to stock')),
                ('payment_impact_json', models.JSONField(default=dict, help_text='Summary of cash/credit adjustments')),
                ('return_impact_json', models.JSONField(default=dict, help_text='Any automatic returns generated')),
                ('resulting_document_id', models.UUIDField(blank=True, help_text='If cancel/reissue, the ID of the new document', null=True)),
                ('linked_credit_note_id', models.UUIDField(blank=True, help_text='Linked credit note if financial values decreased', null=True)),
                ('linked_debit_note_id', models.UUIDField(blank=True, help_text='Linked debit note if financial values increased', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_revisions_created', to=settings.AUTH_USER_MODEL)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_revisions', to='core.outlet')),
            ],
            options={
                'db_table': 'audit_documentrevision',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='audit_docum_content_f56e8a_idx'), models.Index(fields=['outlet', 'created_at'], name='audit_docum_outlet__d66a47_idx')],
            },
        ),
    ]
