# Generated by Django 5.0.3 on 2026-07-04 19:47

from django.db import migrations


def migrate_bill_revisions(apps, schema_editor):
    BillRevision = apps.get_model('billing', 'BillRevision')
    DocumentRevision = apps.get_model('audit', 'DocumentRevision')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    SaleInvoice = apps.get_model('billing', 'SaleInvoice')
    
    # Check if BillRevision exists before trying to migrate (it might not in test setups)
    try:
        sale_invoice_ct = ContentType.objects.get_for_model(SaleInvoice)
    except:
        return
        
    revisions_to_create = []
    for br in BillRevision.objects.all():
        dr = DocumentRevision(
            id=br.id,
            outlet=br.outlet,
            content_type=sale_invoice_ct,
            object_id=br.original_invoice_id,
            revision_number=br.revision_number,
            revision_type=br.revision_type,
            revision_status=br.revision_status,
            modified_by=br.modified_by,
            modified_at=br.modified_at,
            reason_code=br.reason_code,
            reason_text=br.reason_text,
            old_snapshot_json=br.old_snapshot_json,
            new_snapshot_json=br.new_snapshot_json,
            diff_summary_json=br.diff_summary_json,
            stock_impact_json=br.stock_impact_json,
            payment_impact_json=br.payment_impact_json,
            return_impact_json=br.return_impact_json,
            resulting_document_id=br.resulting_invoice_id,
            linked_credit_note_id=br.linked_credit_note_id,
            linked_debit_note_id=br.linked_debit_note_id,
            created_at=br.created_at,
            updated_at=br.updated_at
        )
        revisions_to_create.append(dr)
        
    DocumentRevision.objects.bulk_create(revisions_to_create)

class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0005_documentrevision'),
        ('billing', '0010_saleinvoice_cancellation_reason_and_more'), # Ensure we run after BillRevision exists
    ]

    operations = [
        migrations.RunPython(migrate_bill_revisions, reverse_code=migrations.RunPython.noop),
    ]
