# Generated by Django 5.0.3 on 2026-07-12 21:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0006_migrate_billrevisions'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.CharField(blank=True, max_length=255, null=True)),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_id', models.CharField(blank=True, max_length=255, null=True)),
                ('actor_type', models.CharField(default='human', max_length=50)),
                ('request_id', models.CharField(blank=True, max_length=255, null=True)),
                ('session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('action', models.CharField(db_index=True, max_length=255)),
                ('module', models.CharField(db_index=True, max_length=255)),
                ('entity_type', models.CharField(blank=True, db_index=True, max_length=255)),
                ('entity_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('entity_label', models.CharField(blank=True, max_length=255)),
                ('reason_code', models.CharField(blank=True, max_length=50)),
                ('reason_text', models.TextField(blank=True)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('severity', models.CharField(default='info', max_length=50)),
                ('correlation_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'audit_activity_event',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['module', 'action'], name='audit_activ_module_6146b3_idx'), models.Index(fields=['entity_type', 'entity_id'], name='audit_activ_entity__561aba_idx'), models.Index(fields=['tenant_id', 'occurred_at'], name='audit_activ_tenant__56af36_idx')],
            },
        ),
        migrations.CreateModel(
            name='SystemEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.CharField(blank=True, max_length=255, null=True)),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('event_name', models.CharField(db_index=True, max_length=255)),
                ('component', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
                ('job_id', models.CharField(blank=True, max_length=255, null=True)),
                ('request_id', models.CharField(blank=True, max_length=255, null=True)),
                ('actor_type', models.CharField(default='system', max_length=50)),
                ('entity_type', models.CharField(blank=True, max_length=255)),
                ('entity_id', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(default='success', max_length=50)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('severity', models.CharField(default='info', max_length=50)),
            ],
            options={
                'db_table': 'audit_system_event',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['event_name'], name='audit_syste_event_n_84dfe2_idx'), models.Index(fields=['tenant_id', 'occurred_at'], name='audit_syste_tenant__da37af_idx')],
            },
        ),
        migrations.CreateModel(
            name='DocumentRevisionV2',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.CharField(blank=True, max_length=255, null=True)),
                ('object_id', models.UUIDField()),
                ('entity_type', models.CharField(blank=True, max_length=255)),
                ('revision_no', models.IntegerField(default=1)),
                ('action', models.CharField(max_length=50)),
                ('old_snapshot_json', models.JSONField(blank=True, default=dict)),
                ('new_snapshot_json', models.JSONField(blank=True, default=dict)),
                ('diff_summary_json', models.JSONField(blank=True, default=dict)),
                ('reason_code', models.CharField(blank=True, max_length=50)),
                ('reason_text', models.TextField(blank=True)),
                ('actor_id', models.CharField(blank=True, max_length=255, null=True)),
                ('actor_type', models.CharField(default='human', max_length=50)),
                ('request_id', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'audit_document_revision_v2',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='audit_docum_content_378971_idx'), models.Index(fields=['tenant_id', 'created_at'], name='audit_docum_tenant__5c5bfc_idx')],
            },
        ),
    ]
